### ISSUE TITLE
Bug: There was a problem with the database: Specify a namespace to use

### ISSUE THREAD

**Issue by alniswar19** [surrealdb/surrealdb.net#127]
### Describe the bug

After updating to surreal 2.0, using the same code to query throws error as follows

```
SurrealDb.Net.Exceptions.SurrealDbErrorResultException: Request problems detected
There was a problem with the database: Specify a namespace to use

   at SurrealDb.Net.Internals.SurrealDbHttpEngine.EnsuresFirstResultOk(SurrealDbResponse dbResponse) in /_/SurrealDb.Net/Internals/SurrealDbEngine.Http.cs:line 1030

   at SurrealDb.Net.Internals.SurrealDbHttpEngine.Select[T](String table, CancellationToken cancellationToken) in /_/SurrealDb.Net/Internals/SurrealDbEngine.Http.cs:line 481

```

### Steps to reproduce

Here is my code
```csharp
private readonly ISurrealDbClient _surrealDbClient;

public UserController(ISurrealDbClient surrealDbClientt)
{
    _surrealDbClient = surrealDbClient;
}

// GET: api/<UserController>
[HttpGet]
public async Task<IActionResult> Get(CancellationToken cancellationToken)
{
     var result = await _surrealDbClient.Select<User>("user", cancellationToken);
     return Ok(result);
}
```

### Expected behaviour

returns the data correctly.

### SurrealDB version

surreal 2.0

### Package version(s)

```
Project 'orion.AppHost' has the following package references
   [net8.0]:
   Top-level Package                              Requested   Resolved
   > Aspire.Dashboard.Sdk.win-x64           (A)   [8.2.0, )   8.2.0
   > Aspire.Hosting.AppHost                       8.2.0       8.2.0
   > Aspire.Hosting.NodeJs                        8.2.0       8.2.0
   > Aspire.Hosting.Orchestration.win-x64   (A)   [8.2.0, )   8.2.0
   > Aspire.Hosting.Redis                         8.2.0       8.2.0
   > Aspire.Hosting.Seq                           8.2.0       8.2.0

Project 'orion.ServiceDefaults' has the following package references
   [net8.0]:
   Top-level Package                                   Requested   Resolved
   > Microsoft.Extensions.Http.Resilience              8.8.0       8.8.0
   > Microsoft.Extensions.ServiceDiscovery             8.2.0       8.2.0
   > OpenTelemetry.Exporter.OpenTelemetryProtocol      1.9.0       1.9.0
   > OpenTelemetry.Extensions.Hosting                  1.9.0       1.9.0
   > OpenTelemetry.Instrumentation.AspNetCore          1.9.0       1.9.0
   > OpenTelemetry.Instrumentation.Http                1.9.0       1.9.0
   > OpenTelemetry.Instrumentation.Runtime             1.9.0       1.9.0

Project 'orion.ApiService' has the following package references
   [net8.0]:
   Top-level Package                        Requested   Resolved
   > Aspire.Seq                             8.2.0       8.2.0
   > Swashbuckle.AspNetCore.SwaggerGen      6.7.3       6.7.3
   > Swashbuckle.AspNetCore.SwaggerUI       6.7.3       6.7.3

Project 'orion.Tests' has the following package references
   [net8.0]:
   Top-level Package                Requested   Resolved
   > Aspire.Hosting.Testing         8.2.0       8.2.0
   > coverlet.collector             6.0.2       6.0.2
   > Microsoft.NET.Test.Sdk         17.10.0     17.10.0
   > xunit                          2.9.0       2.9.0
   > xunit.runner.visualstudio      2.8.2       2.8.2

Project 'orion.Domain' has the following package references
   [net8.0]:
   Top-level Package      Requested   Resolved
   > SurrealDb.Net        0.5.1       0.5.1

Project 'orion.Infrastructure' has the following package references
   [net8.0]: No packages were found for this framework.
The project `C:\Work\Git\orion\orion.front\orion.front.esproj` uses package.config for NuGet packages, while the command works only with package reference projects.
```

### Contact Details

al.niswar19@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdaptGit** [comment]
Yea i have this same issues can provide extra info if requred.

**Comment by Odonno** [comment]
Hello @AdaptGit 

This issue exists due to the use of an outdated package that was not compatible with SurrealDB. You should use SurrealDb.Net v0.6.0 or later if using SurrealDB v2.X. 

If it happens you have an issue with SurrealDb.Net v0.6.0, then I suggest you to create a new issue and provide some context about the problem.

Thank you.

**Comment by zengyun261** [comment]
> Hello [@AdaptGit](https://github.com/AdaptGit)
> 
> This issue exists due to the use of an outdated package that was not compatible with SurrealDB. You should use SurrealDb.Net v0.6.0 or later if using SurrealDB v2.X.
> 
> If it happens you have an issue with SurrealDb.Net v0.6.0, then I suggest you to create a new issue and provide some context about the problem.
> 
> Thank you.

In version 0.7 + SurrealDB 2.2.1, the same error occurs when using RocksDB or SurrealKV,
 ConnectionString: Endpoint=surrealkv://a.db;Namespace=test;Database=test
